# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repomedic < Formula
  desc "The Governance Auditor for GitHub Fleets"
  homepage "https://github.com/repomedic/repomedic"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/repomedic/repomedic/releases/download/v1.1.0/repomedic_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "9fe20f9221d4da78a3b053afbd89239e66f4cb2e36385c388579154c7e6443a7"

      def install
        bin.install "repomedic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/repomedic/repomedic/releases/download/v1.1.0/repomedic_1.1.0_Darwin_arm64.tar.gz"
      sha256 "6864177ded5a40fb65c3d41330ee67b29e2b72811bf81e7fc3ebb337a5613738"

      def install
        bin.install "repomedic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/repomedic/repomedic/releases/download/v1.1.0/repomedic_1.1.0_Linux_x86_64.tar.gz"
      sha256 "f4556d42103f6d12eb0ca00bce503180e00678d04c027d9117505783a8623a18"
      def install
        bin.install "repomedic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/repomedic/repomedic/releases/download/v1.1.0/repomedic_1.1.0_Linux_arm64.tar.gz"
      sha256 "a32983670b52b921ac57db42cf24a5179b347bb22f6933e1a49346d9d574bae3"
      def install
        bin.install "repomedic"
      end
    end
  end

  test do
    system "#{bin}/repomedic --version"
  end
end
