# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repomedic < Formula
  desc "The Governance Auditor for GitHub Fleets"
  homepage "https://github.com/repomedic/repomedic"
  version "1.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/repomedic/repomedic/releases/download/v1.0.2/repomedic_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "daab0009ddd9c85a7010ac147b7e9e4112ecaf369cf3750a1d70cbc875663470"

      def install
        bin.install "repomedic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/repomedic/repomedic/releases/download/v1.0.2/repomedic_1.0.2_Darwin_arm64.tar.gz"
      sha256 "0a8935f16b51e75998095942e29360d60ed1cb133e313388dc64c83d2aeff2c5"

      def install
        bin.install "repomedic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/repomedic/repomedic/releases/download/v1.0.2/repomedic_1.0.2_Linux_x86_64.tar.gz"
      sha256 "27e770f09576815253ded7162289fc4d6797eddf7527a06af880808e34f738e8"
      def install
        bin.install "repomedic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/repomedic/repomedic/releases/download/v1.0.2/repomedic_1.0.2_Linux_arm64.tar.gz"
      sha256 "590963a97d57b3c0512aa14ab93a3a0035add5fbf36f7fb91aad320bf545176e"
      def install
        bin.install "repomedic"
      end
    end
  end

  test do
    system "#{bin}/repomedic --version"
  end
end
