# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repomedic < Formula
  desc "The Governance Auditor for GitHub Fleets"
  homepage "https://github.com/repomedic/repomedic"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/repomedic/repomedic/releases/download/v1.1.0/repomedic_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "b6747d9574627d09d671a26f91a4ae9feaac0abd5e4568c0e484ed5ed18fc305"

      def install
        bin.install "repomedic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/repomedic/repomedic/releases/download/v1.1.0/repomedic_1.1.0_Darwin_arm64.tar.gz"
      sha256 "51a6439a3e6b69c29608956081909950a572ad9a6b0f01ca30b0a1e017fac84a"

      def install
        bin.install "repomedic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/repomedic/repomedic/releases/download/v1.1.0/repomedic_1.1.0_Linux_x86_64.tar.gz"
      sha256 "f63d399648ff4cda4052aabaaa0a8712b6f1c6f0f3d235eaa326a8a21b6ab579"
      def install
        bin.install "repomedic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/repomedic/repomedic/releases/download/v1.1.0/repomedic_1.1.0_Linux_arm64.tar.gz"
      sha256 "098715932bd0f98635c049b1c98f2389df2bad092a8931a3b8cca7c1709f697f"
      def install
        bin.install "repomedic"
      end
    end
  end

  test do
    system "#{bin}/repomedic --version"
  end
end
